[versions]
#commons-math3 = "3.6.1"
#guava = "33.5.0-jre"
dokka = "2.2.0"

[libraries]
#commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
#guava = { module = "com.google.guava:guava", version.ref = "guava" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.4.20" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
