import org.gradle.api.tasks.testing.logging.TestLogEvent

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.7.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.slf4j:slf4j-api:2.1.0-alpha1")
    @Suppress("VulnerableLibrariesLocal", "RedundantSuppression")
    implementation("ch.qos.logback:logback-classic:1.5.38")
    implementation("org.apache.logging.log4j:log4j-core:3.0.0-beta3")
    implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.8.0-0.6.x-compat")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0")
    testImplementation("com.zaxxer:HikariCP:7.1.0")
    testImplementation("com.h2database:h2:2.5.250")
    testImplementation("org.postgresql:postgresql:42.7.13")
    testImplementation("org.mariadb.jdbc:mariadb-java-client:3.5.2")
    testImplementation("io.kotest.extensions:kotest-extensions-testcontainers:2.0.2")
    testImplementation("org.testcontainers:postgresql:1.21.4")
    testImplementation("org.testcontainers:mariadb:1.21.4")
}

testing {
    suites {
        // Configure the built-in test suite
        @Suppress("UnstableApiUsage") val test = named<JvmTestSuite>("test") {
            // Use Kotlin Test test framework
            useKotlinTest("2.4.0")
        }
    }
}

tasks {
    withType<Test> {
        testLogging {
            events = setOf(TestLogEvent.PASSED, TestLogEvent.SKIPPED, TestLogEvent.FAILED)
            showExceptions = true
            showCauses = true
            showStackTraces = true
        }
    }
    withType<Jar> {
        archiveAppendix = archiveBaseName.get()
        archiveBaseName = "kse"
    }
}

//// Apply a specific Java toolchain to ease working on different environments.
//java {
//    toolchain {
//        languageVersion = JavaLanguageVersion.of(21)
//    }
//}

kotlin {
    jvmToolchain(21)
    compilerOptions {
        freeCompilerArgs.add("-Xcollection-literals")
        freeCompilerArgs.add("-Xintrinsic-const-evaluation")
        freeCompilerArgs.add("-Xcontext-sensitive-resolution")
    }
}

