package wafna.kse

import java.sql.Connection

/** An element of the projection that maps to an object These are used to generate SQL. */
data class Field(val name: String, val sqlType: String? = null, val autoGenerated: Boolean = false) {
    init {
        require(name.isNotEmpty()) { "Field name required." }
        require(sqlType?.isEmpty() != true) { "sqlType must be non-empty if provided." }
    }
}

/** Syntactic convenience. */
fun String.field(sqlType: String? = null) = Field(this, sqlType)

val Field.auto: Field
    get() = copy(autoGenerated = true)

/** Syntactic convenience. */
val String.field: Field
    get() = Field(this, null)

/** The fully qualified table name. */
data class Table(val schemas: List<String>, val tableName: String) {
    init {
        require(schemas.all { it.isNotEmpty() }) {
            "Empty schema names prohibited: ${schemas.joinToString(", ") { "\"$it\"" }}"
        }
        require(tableName.isNotEmpty()) { "Empty table name prohibited." }
    }

    constructor(tableName: String) : this(emptyList(), tableName)

    context(_: Connection)
    fun qname() = (schemas + tableName).quoteIdentifiers()

    override fun toString(): String = throw NotImplementedError("Do not use.")
}

/**
 * A mapping between fields in a single table and one or two data classes.
 * The R and W types handle the difference between the nascent record type, without auto-generated fields, that is to
 * be written to the database and the completed records that are selected from the database, namely the id fields.
 * The W type must contain a subset of the fields in R in the same order.
 * This is because fields can be marked as auto-generated and will not be specified when the W type is inserted.
 * It is expected that updates will target specific fields.
 * Note that the same record object can be used for both R and W, even with auto-generated fields.
 * @param R The type of the record to select.
 * @param W The type of the record to insert.
 */
abstract class Entity<R, W>(val table: Table, val fields: List<Field>) {
    init {
        val duplicates = fields.groupBy { it.name }.filter { 1 < it.value.size }
        require(duplicates.isEmpty()) {
            "Duplicate fields detected: ${duplicates.keys.joinToString(", ")}."
        }
    }

    /**
     * Implementation-specific record reader.
     * The return type simplifies the implementation.
     * @return A function that reads a record R from a result.
     */
    abstract fun read(): ResultIterator.() -> R

    /**
     * Implementation-specific record writer.
     * The return type simplifies the implementation.
     * Some types require the connection, namely java.sql.Array, hence the context.
     * @return A function that creates a list of parameter setters in the order of the fields from a record W.
     */
    context(cx: Connection)
    abstract fun write(): W.() -> List<Param>

    /** Generates the comma-separated list of alias-qualified field names. */
    private fun projection(alias: String): String = fields.joinToString(", ") {
        if (alias.isEmpty()) "\"${it.name}\"" else "\"$alias\".\"${it.name}\""
    }

    /** Generates the head of a SELECT statement. */
    context(_: Connection)
    private fun selectHead(alias: String = ""): String =
        "SELECT ${projection(alias)}\nFROM ${table.qname()}${if (alias.isEmpty()) " " else " \"$alias\""}"

    /** SELECT <<alias>>.projection FROM table <<alias>> <<tail>> */
    context(_: Connection, _: Listener)
    suspend fun select(
        alias: String,
        tail: String,
        vararg params: Param,
    ): List<R> = select("${selectHead(alias)}\n$tail", *params) { readRecords(read()) }

    /** SELECT <<alias>>.projection FROM table <<alias>> <<tail>> */
    context(c_: Connection, _: Listener)
    suspend fun select(
        alias: String,
        tail: String,
        params: Collection<Param>,
    ): List<R> =
        select("${selectHead(alias)}\n$tail", *params.toTypedArray()) {
            readRecords(read())
        }

    /** INSERT INTO table (<<field-names>>) VALUES (<<records>>) */
    context(_: Connection, _: Listener)
    suspend fun insert(
        records: Iterable<W>,
    ): IntArray {
        val iterator = records.iterator()
        if (!iterator.hasNext())
            return IntArray(0)
        val fieldNames = fields.mapNotNull { if (it.autoGenerated) null else it.name }
        return insert(
            sql = """INSERT INTO ${table.qname()} (${fieldNames.joinToString(", ") { it.quoteIdentifier() }})
                VALUES (${parameterList(namesToFields(fieldNames))})""".trimIndent(),
            records = iterator.map { it.(write())() }, // C++!
        )
    }

    /** UPDATE table SET <<field-names>> WHERE <<where>> */
    context(_: Connection, _: Listener)
    suspend fun update(
        fieldNames: Iterable<String>,
        where: String,
        vararg params: Param,
    ): Int = update(
        sql = "UPDATE ${table.qname()}\nSET ${fieldList(namesToFields(fieldNames))}\nWHERE $where",
        params = params,
    )

    /** UPDATE table SET <<field-names>> WHERE <<where>> */
    context(_: Connection, _: Listener)
    suspend fun update(
        fieldNames: Iterable<String>,
        where: String,
        params: Collection<Param>,
    ): Int = update(
        sql = "UPDATE ${table.qname()}\nSET ${fieldList(namesToFields(fieldNames))}\nWHERE $where",
        params = params,
    )

    private val fieldMap = fields.associateBy { it.name }

    private fun namesToFields(names: Iterable<String>): List<Field> =
        names.map { fieldMap[it] ?: error("Unknown field \"$it\"") }

    companion object {
        private fun parameterList(fields: Iterable<Field>): String =
            fields.joinToString(", ") {
                when (val sqlType = it.sqlType) {
                    null -> "?"
                    else -> "? :: $sqlType"
                }
            }

        private fun fieldList(fields: Iterable<Field>): String =
            fields.joinToString(", ") {
                when (val sqlType = it.sqlType) {
                    null -> "\"${it.name}\" = ?"
                    else -> "\"${it.name}\" = ? :: $sqlType"
                }
            }

        private inline fun <P, Q> Iterator<P>.map(crossinline f: (P) -> Q): Iterator<Q> {
            return object : Iterator<Q> {
                override fun next(): Q = f(this@map.next())
                override fun hasNext(): Boolean = this@map.hasNext()
            }
        }
    }
}
