package wafna.kse.aspects

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import wafna.kse.Param
import wafna.kse.pgsql.withPGDB
import wafna.kse.setInt
import wafna.kse.setNullable
import wafna.kse.update
import wafna.kse.withTransaction
import java.sql.Connection

object UserDao :
    Selectable<User> by selectable(UserEntity),
    Insertable<UserWip> by insertable(UserEntity)

object DocumentDao :
    Selectable<Document> by selectable(DocumentEntity),
    Insertable<DocumentWip> by insertable(DocumentEntity)

class TestAspect {
    @Test
    fun testAspect() {
        // Worth the test performance penalty to use PG in docker than H2 in memory. :(
        withPGDB { db ->
            db.withTransaction {
                update(
                    """CREATE TABLE users (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                    name VARCHAR(255) NOT NULL
                    )""".trimIndent()
                )
                update(
                    """CREATE TABLE documents (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                    name VARCHAR(255) NOT NULL, 
                    owner_id INT references users(id) NOT NULL
                    )""".trimIndent()
                )
                val usernames = listOf("Bob", "Carol", "Ted", "Alice")
                UserDao.insert(usernames.map { UserWip(it) })
                val users = UserDao.searchByName("%")
                assertEquals(usernames.size, users.size)
                UserDao.selectByIds(users.map { it.id }).also {
                    assertEquals(users.size, it.size)
                }
                // Create documents for each user.
                val docsPerUser = 3
                DocumentDao.insert(users.flatMap { user ->
                    (1..docsPerUser).map {
                        DocumentWip(
                            "${user.name} Document $it",
                            user.id
                        )
                    }
                })
                users.forEach { user ->
                    val docs = DocumentEntity.select("d", "WHERE d.owner_id = ?", user.id.setInt())
                    assertEquals(docsPerUser, docs.size)
                    assertTrue(docs.all { it.ownerId == user.id })
                    assertTrue(docs.all { it.name.startsWith(user.name) })
                }
            }
        }
    }
}

context(cx: Connection)
fun Collection<Int>?.setIds(): Param =
    setNullable { statement, position, value ->
        statement.setArray(position, cx.createArrayOf("TEXT", value.toTypedArray()))
    }
